swarm:
  datasources:
    jdbc-drivers:
      h2:
        driver-class-name: org.h2.Driver
        xa-datasource-class-name: org.h2.jdbcx.JdbcDataSource
        driver-module-name: com.h2database.h2
    data-sources:
      ExampleDS:
        driver-name: h2
        connection-url: "
        user-name: sa
        password: sa